[package]
name = "threadpool-demo"
version = "0.1.0"
authors = ["ratnadeepb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
image = "0.23.10"
num = "0.3.0"
num_cpus = "1.13"
error-chain = "0.12.4"