[package]
name = "hello-tokio"
version = "0.1.0"
authors = ["ratnadeepb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { features=["full"], version = "0.3.2" }
libc = "0.2.80"
